### ISSUE TITLE
Gitian descriptors still refer to Bitcoin

### ISSUE THREAD

**Issue by JeremyRand** [domob1812/namecore#6]
Building with Gitian does not work out of the box, because the Gitian descriptors point to the Bitcoin GitHub repo, and list the output name as Bitcoin.  See https://github.com/domob1812/namecore/blob/master/contrib/gitian-descriptors/gitian-linux.yml#L2 , https://github.com/domob1812/namecore/blob/master/contrib/gitian-descriptors/gitian-linux.yml#L20 , and https://github.com/domob1812/namecore/blob/master/contrib/gitian-descriptors/gitian-linux.yml#L21 for the ones that jump out at me on Linux.  (I assume the same issues exist in Windows and OS X, but I haven't checked.)

I guess these should be replaced with the Namecoin name, and the namecoin/namecoin GitHub repo (after @domob1812 moves this code there).  If for some reason we're not able to move the repo to namecoin/namecoin in the foreseeable future, then pointing to this repo would be an acceptable interim step.

**Comment by JeremyRand** [comment]
There are also a few other references to paths/files with "bitcoin" in them.  Those should be changed too.

**Comment by domob1812** [comment]
I agree regarding the Gitian descriptors.  Feel free to create a pull request once I've created a namecoin/namecoin branch.

For other paths:  I think that only user visible things should be changed.  I prefer to keep things like "libbitcoinconsensus" (if that's what you mean) unchanged, since that minimises unnecessary changes in comparison to the Bitcoin codebase.  Those changes only make future maintainance more involved (I had to manually resolve conflicts due to changes in the Makefiles alone multiple times already over the small time that Namecoin Core exists now - changing *all* the library names and so on would have made that worse by an order of magnitude).

**Comment by JeremyRand** [comment]
I may be able to send in a PR fixing most of this within the next few days, if no one else gets to it before I do.

**Comment by JeremyRand** [comment]
@domob1812 I'm referring to the Gitian input/output filenames.  Leaving them named "bitcoin" will cause conflicts if the same Gitian builder tries to build both Bitcoin and Namecoin.  I certainly wouldn't change the library names.

**Comment by domob1812** [comment]
Ok, in that case, I'm definitely fine with that!  Feel free to do whatever you deem necessary with respect to Gitian.

**Comment by domob1812** [comment]
Is this still relevant?

**Comment by JeremyRand** [comment]
@domob1812 I believe this is fixed; feel free to close.
